### ISSUE TITLE
Missing download link on website 

### ISSUE THREAD

**Issue by AmirBraham** [michealparks/galeri#3]
Clicking download icon simply refreshes the page . I inspected incoming requests and figured that you exceeded api rate limit while fetching this link : https://api.github.com/repos/michealparks/galeri-www/releases/latest

**Comment by michealparks** [comment]
@AmirBraham thanks for the info! I hadn't expected a recent bump in interest in this project, I think I may have to move funneling downloads away from github if this continues.
